[package]
name = "iss_ratatui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.24.0", features = ["all-widgets"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = { version = "1.0.107" }
